name: Check run

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - run: sudo systemctl start nginx

    - name: ZAP Plan
      uses: ./
      id: af-plan
      with:
        plan: '.zap/AFplan.yml'
