on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-af@v0.1.0
        with:
          plan: '.github/workflows/AFzap.yml'
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          # target: 'http://localhost/DVWA/'
          # cmd_options: '-a'
