---
env:
  contexts:
  - name: "Context"
    urls:
    - "http://localhost/DVWA/"
  parameters:
    failOnError: true
    failOnWarning: true
    progressToStdout: true
jobs:
- requests:
  - url: "http://localhost/DVWA/"
  type: "requestor"
