on: 
  push:
  schedule:
    - cron: '0 22 * * *' # Runs at 6 AM GMT+8 every day

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Check Docker daemon status
        run: |
          sudo systemctl status docker || true
          docker info || true
          
      - name: Replacing Password
        env:
          ZAP_PASSWORD: ${{secrets.ZAP_PASSWORD}}
        run: |
          sed -ie "s/PASSWORD/${ZAP_PASSWORD}/" $GITHUB_WORKSPACE/Authentication.context
      
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://google-gruyere.appspot.com/359590344817771210252875530455144199549/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j -d -m "1" -U "test123" -n /zap/wrk/Authentication.context'

      # You can configure to blacklist some websites from being attacked
  # Or ignore certain findings that are insignificant by configuring
# a .tsv file (.zap/rules.tsv)

