on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Website
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'https://google-gruyere.appspot.com/359590344817771210252875530455144199549/'
